spring:
  application:
    name: module-core-api
  profiles:
    default: local
    active: ${spring.profiles.default}
  config:
    import:
      - core-business.yml

server:
  port: 18080
  servlet:
    context-path: /api/core