version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
