spring:
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.SpringPhysicalNamingStrategy


decorator:
  datasource:
    p6spy:
      enable-logging: true
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR